#!/bin/sh
#
# Run this script one time to initialize a Release build using
# a build.ninja file here.
#
# This script will have cmake generate a build.ninja and then
# build a Release version of rawscan using that build.ninja.
#
# Once this script is run, subsequent rebuilds can be done by issuing
# the simple command "ninja" in this directory.  Cmake remembers in
# the CMakeCache.txt file that it creates in this directory that it
# is to build "Release" versions, and the build.ninja that it generated
# does that.
#
# Furthermore, this Release build can then be installed on the
# present system by issuing "ninja install" as root.
#
# Paul Jackson
# pj@usa.net
# 5 Dec 2019

cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release ../../source
cmake --build .
