# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pj/etc/rawscan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pj/etc/rawscan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pj/etc/rawscan/CMakeFiles /home/pj/etc/rawscan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pj/etc/rawscan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named random_line_generator

# Build rule for target.
random_line_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 random_line_generator
.PHONY : random_line_generator

# fast build rule for target.
random_line_generator/fast:
	$(MAKE) -f CMakeFiles/random_line_generator.dir/build.make CMakeFiles/random_line_generator.dir/build
.PHONY : random_line_generator/fast

#=============================================================================
# Target rules for targets named rawscan

# Build rule for target.
rawscan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawscan
.PHONY : rawscan

# fast build rule for target.
rawscan/fast:
	$(MAKE) -f CMakeFiles/rawscan.dir/build.make CMakeFiles/rawscan.dir/build
.PHONY : rawscan/fast

#=============================================================================
# Target rules for targets named rawscantest

# Build rule for target.
rawscantest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawscantest
.PHONY : rawscantest

# fast build rule for target.
rawscantest/fast:
	$(MAKE) -f CMakeFiles/rawscantest.dir/build.make CMakeFiles/rawscantest.dir/build
.PHONY : rawscantest/fast

lib/rawscan.o: lib/rawscan.c.o

.PHONY : lib/rawscan.o

# target to build an object file
lib/rawscan.c.o:
	$(MAKE) -f CMakeFiles/rawscan.dir/build.make CMakeFiles/rawscan.dir/lib/rawscan.c.o
.PHONY : lib/rawscan.c.o

lib/rawscan.i: lib/rawscan.c.i

.PHONY : lib/rawscan.i

# target to preprocess a source file
lib/rawscan.c.i:
	$(MAKE) -f CMakeFiles/rawscan.dir/build.make CMakeFiles/rawscan.dir/lib/rawscan.c.i
.PHONY : lib/rawscan.c.i

lib/rawscan.s: lib/rawscan.c.s

.PHONY : lib/rawscan.s

# target to generate assembly for a file
lib/rawscan.c.s:
	$(MAKE) -f CMakeFiles/rawscan.dir/build.make CMakeFiles/rawscan.dir/lib/rawscan.c.s
.PHONY : lib/rawscan.c.s

src/rawscanstresstest.o: src/rawscanstresstest.c.o

.PHONY : src/rawscanstresstest.o

# target to build an object file
src/rawscanstresstest.c.o:
	$(MAKE) -f CMakeFiles/rawscantest.dir/build.make CMakeFiles/rawscantest.dir/src/rawscanstresstest.c.o
.PHONY : src/rawscanstresstest.c.o

src/rawscanstresstest.i: src/rawscanstresstest.c.i

.PHONY : src/rawscanstresstest.i

# target to preprocess a source file
src/rawscanstresstest.c.i:
	$(MAKE) -f CMakeFiles/rawscantest.dir/build.make CMakeFiles/rawscantest.dir/src/rawscanstresstest.c.i
.PHONY : src/rawscanstresstest.c.i

src/rawscanstresstest.s: src/rawscanstresstest.c.s

.PHONY : src/rawscanstresstest.s

# target to generate assembly for a file
src/rawscanstresstest.c.s:
	$(MAKE) -f CMakeFiles/rawscantest.dir/build.make CMakeFiles/rawscantest.dir/src/rawscanstresstest.c.s
.PHONY : src/rawscanstresstest.c.s

tests/random_line_generator.o: tests/random_line_generator.c.o

.PHONY : tests/random_line_generator.o

# target to build an object file
tests/random_line_generator.c.o:
	$(MAKE) -f CMakeFiles/random_line_generator.dir/build.make CMakeFiles/random_line_generator.dir/tests/random_line_generator.c.o
.PHONY : tests/random_line_generator.c.o

tests/random_line_generator.i: tests/random_line_generator.c.i

.PHONY : tests/random_line_generator.i

# target to preprocess a source file
tests/random_line_generator.c.i:
	$(MAKE) -f CMakeFiles/random_line_generator.dir/build.make CMakeFiles/random_line_generator.dir/tests/random_line_generator.c.i
.PHONY : tests/random_line_generator.c.i

tests/random_line_generator.s: tests/random_line_generator.c.s

.PHONY : tests/random_line_generator.s

# target to generate assembly for a file
tests/random_line_generator.c.s:
	$(MAKE) -f CMakeFiles/random_line_generator.dir/build.make CMakeFiles/random_line_generator.dir/tests/random_line_generator.c.s
.PHONY : tests/random_line_generator.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... random_line_generator"
	@echo "... rebuild_cache"
	@echo "... rawscan"
	@echo "... rawscantest"
	@echo "... lib/rawscan.o"
	@echo "... lib/rawscan.i"
	@echo "... lib/rawscan.s"
	@echo "... src/rawscanstresstest.o"
	@echo "... src/rawscanstresstest.i"
	@echo "... src/rawscanstresstest.s"
	@echo "... tests/random_line_generator.o"
	@echo "... tests/random_line_generator.i"
	@echo "... tests/random_line_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

